apiVersion: v2
name: whoogle
description: A self hosted search engine on Kubernetes
type: application
version: 0.1.0
appVersion: 0.7.2

icon: https://github.com/benbusby/whoogle-search/raw/main/app/static/img/favicon/favicon-96x96.png

sources:
  - https://github.com/benbusby/whoogle-search
  - https://gitlab.com/benbusby/whoogle-search
  - https://gogs.benbusby.com/benbusby/whoogle-search

keywords:
  - whoogle
  - degoogle
  - search
  - google
  - search-engine
  - privacy
  - tor
  - python
